// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include <math.h>   // isnan
// system
#include <time.h>
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
#include <sys/epoll.h>
// C++
#include <string>
#include <vector>
#include <unordered_set>
#include <unordered_map>
// proj
#include "common.h"
#include "hashtable.h"
#include "zset.h"
#include "list.h"
#include "heap.h"
#include "thread_pool.h"
#include "vdb.h"
#include "python_worker.h"
#include "persist.h"

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static uint64_t get_monotonic_msec() {
    struct timespec tv = {0, 0};
    clock_gettime(CLOCK_MONOTONIC, &tv);
    return uint64_t(tv.tv_sec) * 1000 + tv.tv_nsec / 1000 / 1000;
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer

typedef std::vector<uint8_t> Buffer;

// append to the back
static void buf_append(Buffer &buf, const uint8_t *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(Buffer &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

struct Conn {
    int fd = -1;
    // protocol
    enum Proto { PROTO_BINARY, PROTO_RESP } proto = PROTO_BINARY;

    bool pubsub_mode = false;
    std::unordered_set<std::string> subscriptions;

    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming;    // data to be parsed by the application
    size_t incoming_start = 0;
    Buffer outgoing;    // responses generated by the application
    // timer
    uint64_t last_active_ms = 0;
    DList idle_node;
};

static std::unordered_map<std::string, std::unordered_set<Conn*>>  channels;

static void conn_consume_incoming(Conn* conn, size_t n) {
    conn->incoming_start += n;
    if (conn->incoming_start >= conn->incoming.size()) {
        conn->incoming.clear();
        conn->incoming_start = 0;
    }
    return;
}

// global states
static struct {
    HMap db;
    VDB vdb;
    PyWorker py_worker;
    // a map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;
    // timers for idle connections
    DList idle_list;
    // timers for TTLs
    std::vector<HeapItem> heap;
    // the thread pool
    ThreadPool thread_pool;
} g_data;
static int epfd = -1;

static void handle_sigint(int) {
    pyworker_stop(&g_data.py_worker);
    exit(0);
}


// application callback when the listening socket is ready
static int32_t handle_accept(int epfd, int fd, Conn::Proto proto) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return -1;
    }
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
        ntohs(client_addr.sin_port)
    );

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a `struct Conn`
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->proto = proto;
    conn->want_read = true;
    conn->last_active_ms = get_monotonic_msec();
    dlist_init(&conn->idle_node);

    epoll_event ev{};
    ev.events = EPOLLIN;
    ev.data.ptr = conn;

    if (epoll_ctl(epfd, EPOLL_CTL_ADD, conn->fd, &ev) < 0) {
        msg_errno("epoll_ctl() error");
        delete conn;
        close(connfd);
        return -1;
    }

    dlist_insert_before(&g_data.idle_list, &conn->idle_node);

    // put it into the map
    if (g_data.fd2conn.size() <= (size_t)conn->fd) {
        g_data.fd2conn.resize(conn->fd + 1);
    }
    assert(!g_data.fd2conn[conn->fd]);
    g_data.fd2conn[conn->fd] = conn;
    return 0;
}

static void conn_destroy(int epfd, Conn *conn) {
    epoll_ctl(epfd, EPOLL_CTL_DEL, conn->fd, nullptr);
    (void)close(conn->fd);
    g_data.fd2conn[conn->fd] = NULL;
    dlist_detach(&conn->idle_node);

    for (const auto& channel_name : conn->subscriptions) {
        auto it = channels.find(channel_name);
        if (it == channels.end()) {
            continue;
        }
        it->second.erase(conn);
        if (it->second.empty()) {
            channels.erase(it);
        }
    }

    delete conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) {
    if (cur + 4 > end) {
        return false;
    }
    memcpy(&out, cur, 4);
    cur += 4;
    return true;
}

static bool
read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out) {
    if (cur + n > end) {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t
parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// error code for TAG_ERR
enum {
    ERR_UNKNOWN = 1,    // unknown command
    ERR_TOO_BIG = 2,    // response too big
    ERR_BAD_TYP = 3,    // unexpected value type
    ERR_BAD_ARG = 4,    // bad arguments
};

// data types of serialized data
enum {
    TAG_NIL = 0,    // nil
    TAG_ERR = 1,    // error code + msg
    TAG_STR = 2,    // string
    TAG_INT = 3,    // int64
    TAG_DBL = 4,    // double
    TAG_ARR = 5,    // array
};

// help functions for the serialization
static void buf_append_u8(Buffer &buf, uint8_t data) {
    buf.push_back(data);
}
static void buf_append_u32(Buffer &buf, uint32_t data) {
    buf_append(buf, (const uint8_t *)&data, 4);
}
static void buf_append_i64(Buffer &buf, int64_t data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}
static void buf_append_dbl(Buffer &buf, double data) {
    buf_append(buf, (const uint8_t *)&data, 8);
}

// append serialized data types to the back
static void out_nil(Buffer &out) {
    buf_append_u8(out, TAG_NIL);
}
static void out_str(Buffer &out, const char *s, size_t size) {
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t *)s, size);
}
static void out_int(Buffer &out, int64_t val) {
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}
static void out_dbl(Buffer &out, double val) {
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}
static void out_err(Buffer &out, uint32_t code, const std::string &msg) {
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t *)msg.data(), msg.size());
}
static void out_arr(Buffer &out, uint32_t n) {
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
}
static size_t out_begin_arr(Buffer &out) {
    out.push_back(TAG_ARR);
    buf_append_u32(out, 0);     // filled by out_end_arr()
    return out.size() - 4;      // the `ctx` arg
}
static void out_end_arr(Buffer &out, size_t ctx, uint32_t n) {
    assert(out[ctx - 1] == TAG_ARR);
    memcpy(&out[ctx], &n, 4);
}

// ============================================================
// RESP protocol serialization
// ============================================================

static void out_resp_null(Buffer &out) {
    const char* s = "$-1\r\n";
    buf_append(out, (const uint8_t*)s, strlen(s));
}
static void out_resp_str(Buffer &out, const std::string &s) {
    std::string r = "$" + std::to_string(s.size()) + "\r\n" + s + "\r\n";
    buf_append(out, (const uint8_t *)r.data(), r.size());
}
static void out_resp_int(Buffer &out, int64_t n) {
    std::string r = ":" + std::to_string(n) + "\r\n";
    buf_append(out, (const uint8_t *)r.data(), r.size());
}
static void out_resp_dbl(Buffer &out, double n) {
    std::string r = "$" + std::to_string(snprintf(NULL, 0, "%.17g", n)) + "\r\n";
    char buf[64];
    snprintf(buf, sizeof(buf), "%.17g", n);
    r += buf;
    r += "\r\n";
    buf_append(out, (const uint8_t *)r.data(), r.size());
}
static void out_resp_err(Buffer &out, const std::string &msg) {
    std::string r = "-ERR " + msg + "\r\n";
    buf_append(out, (const uint8_t *)r.data(), r.size());
}
static void out_resp_arr_header(Buffer &out, uint32_t n) {
    std::string r = "*" + std::to_string(n) + "\r\n";
    buf_append(out, (const uint8_t *)r.data(), r.size());
}
static void out_resp_str_array(Buffer &out, std::initializer_list<std::string> items) {
    out_resp_arr_header(out, items.size());
    for (const auto &s : items) {
        out_resp_str(out, s);
    }
}
// value types
enum {
    T_INIT  = 0,
    T_STR   = 1,    // string
    T_ZSET  = 2,    // sorted set
};

// KV pair for the top-level hashtable
struct Entry {
    struct HNode node;      // hashtable node
    std::string key;
    // for TTL
    size_t heap_idx = -1;   // array index to the heap item
    // value
    uint32_t type = 0;
    // one of the following
    std::string str;
    ZSet zset;
};

static Entry *entry_new(uint32_t type) {
    Entry *ent = new Entry();
    ent->type = type;
    return ent;
}

static void entry_set_ttl(Entry *ent, int64_t ttl_ms);

static void entry_del_sync(Entry* ent) {
    if (ent->type == T_ZSET) {
        zset_clear(&ent->zset);
    }
    delete ent;
}

static void entry_del_func(void *arg) {
    entry_del_sync((Entry *)arg);
}

static void entry_del(Entry *ent) {
    // unlink it from any data structures
    entry_set_ttl(ent, -1); // remove from the heap data structure
    // run the destructor in a thread pool for large data structures
    size_t set_size = (ent->type == T_ZSET) ? hm_size(&ent->zset.hmap) : 0;
    const size_t k_large_container_size = 1000;
    if (set_size > k_large_container_size) {
        thread_pool_queue(&g_data.thread_pool, &entry_del_func, ent);
    } else {
       entry_del_sync(ent); 
    }
}

struct LookupKey {
    struct HNode node;  // hashtable node
    std::string key;
};

static void conn_update_events(int epfd, Conn *conn);

// equality comparison for the top-level hashstable
static bool entry_eq(HNode *node, HNode *key) {
    struct Entry *ent = container_of(node, struct Entry, node);
    struct LookupKey *keydata = container_of(key, struct LookupKey, node);
    return ent->key == keydata->key;
}

static void do_get(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node) {
        return resp ? out_resp_null(out) : out_nil(out);
    }
    // copy the value
    Entry *ent = container_of(node, Entry, node);
    if (ent->type != T_STR) {
        return resp
            ? out_resp_err(out, "not a string value")
            : out_err(out, ERR_BAD_TYP, "not a string value");
    }
    return resp 
        ? out_resp_str(out, ent->str)
        : out_str(out, ent->str.data(), ent->str.size());
}

static void do_set(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node) {
        // found, update the value
        Entry *ent = container_of(node, Entry, node);
        if (ent->type != T_STR) {
            return resp
                ? out_resp_err(out, "a non-string value exists")
                : out_err(out, ERR_BAD_TYP, "a non-string value exists");
        }
        ent->str.swap(cmd[2]);
    } else {
        // not found, allocate & insert a new pair
        Entry *ent = entry_new(T_STR);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->str.swap(cmd[2]);
        hm_insert(&g_data.db, &ent->node);
    }
    return resp ? out_resp_str(out, "OK") : out_nil(out);
}

static void do_del(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    // hashtable delete
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if (node) { // deallocate the pair
        entry_del(container_of(node, Entry, node));
    }
    return resp 
        ? out_resp_int(out, node ? 1 : 0)
        : out_int(out, node ? 1 : 0);
}

static void heap_delete(std::vector<HeapItem> &a, size_t pos) {
    // swap the erased item with the last item
    a[pos] = a.back();
    a.pop_back();
    // update the swapped item
    if (pos < a.size()) {
        heap_update(a.data(), pos, a.size());
    }
}

static void heap_upsert(std::vector<HeapItem> &a, size_t pos, HeapItem t) {
    if (pos < a.size()) {
        a[pos] = t;         // update an existing item
    } else {
        pos = a.size();
        a.push_back(t);     // or add a new item
    }
    heap_update(a.data(), pos, a.size());
}

// set or remove the TTL
static void entry_set_ttl(Entry *ent, int64_t ttl_ms) {
    if (ttl_ms < 0 && ent->heap_idx != (size_t)-1) {
        // setting a negative TTL means removing the TTL
        heap_delete(g_data.heap, ent->heap_idx);
        ent->heap_idx = -1;
    } else if (ttl_ms >= 0) {
        // add or update the heap data structure
        uint64_t expire_at = get_monotonic_msec() + (uint64_t)ttl_ms;
        HeapItem item = {expire_at, &ent->heap_idx};
        heap_upsert(g_data.heap, ent->heap_idx, item);
    }
}

static bool str2int(const std::string &s, int64_t &out) {
    char *endp = NULL;
    out = strtoll(s.c_str(), &endp, 10);
    return endp == s.c_str() + s.size();
}

// PEXPIRE key ttl_ms
static void do_expire(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    int64_t ttl_ms = 0;
    if (!str2int(cmd[2], ttl_ms)) {
        return resp
            ? out_resp_err(out, "expect int64")
            : out_err(out, ERR_BAD_ARG, "expect int64");
    }

    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node) {
        Entry *ent = container_of(node, Entry, node);
        entry_set_ttl(ent, ttl_ms);
    }
    return resp
        ? out_resp_int(out, node ? 1 : 0)
        : out_int(out, node ? 1 : 0);
}

// PTTL key
static void do_ttl(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node) {
        return resp ? out_resp_int(out, -2) : out_int(out, -2);
    }

    Entry *ent = container_of(node, Entry, node);
    if (ent->heap_idx == (size_t)-1) {
       return resp ? out_resp_int(out, -1) : out_int(out, -1);
    }

    uint64_t expire_at = g_data.heap[ent->heap_idx].val;
    uint64_t now_ms = get_monotonic_msec();
    int64_t ttl = expire_at > now_ms ? (expire_at - now_ms) : 0;
    return resp ? out_resp_int(out, ttl) : out_int(out, ttl);
}

static bool cb_keys(HNode *node, void *arg) {
    Buffer &out = *(Buffer *)arg;
    const std::string &key = container_of(node, Entry, node)->key;
    out_str(out, key.data(), key.size());
    return true;
}
static bool cb_keys_resp(HNode *node, void *arg) {
    Buffer &out = *(Buffer *)arg;
    const std::string &key = container_of(node, Entry, node)->key;
    out_resp_str(out, key);
    return true;
}

static void do_keys(std::vector<std::string> &, Buffer &out, bool resp) {
    if (resp) {
        out_resp_arr_header(out, (uint32_t)hm_size(&g_data.db));
        hm_foreach(&g_data.db, &cb_keys_resp, (void *)&out);
    } else {
        out_arr(out, (uint32_t)hm_size(&g_data.db));
        hm_foreach(&g_data.db, &cb_keys, (void *)&out);
    }
}

static bool str2dbl(const std::string &s, double &out) {
    char *endp = NULL;
    out = strtod(s.c_str(), &endp);
    return endp == s.c_str() + s.size() && !isnan(out);
}

// zadd zset score name
static void do_zadd(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return resp
            ? out_resp_err(out, "expect float")
            : out_err(out, ERR_BAD_ARG, "expect float");
    }

    // look up or create the zset
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);

    Entry *ent = NULL;
    if (!hnode) {   // insert a new key
        ent = entry_new(T_ZSET);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    } else {        // check the existing key
        ent = container_of(hnode, Entry, node);
        if (ent->type != T_ZSET) {
            return resp
                ? out_resp_err(out, "expect zset")
                : out_err(out, ERR_BAD_TYP, "expect zset");
        }
    }

    // add or update the tuple
    const std::string &name = cmd[3];
    bool added = zset_insert(&ent->zset, name.data(), name.size(), score);
    return resp
        ? out_resp_int(out, (int64_t)added)
        : out_int(out, (int64_t)added);
}

static const ZSet k_empty_zset;

static ZSet *expect_zset(std::string &s) {
    LookupKey key;
    key.key.swap(s);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!hnode) {   // a non-existent key is treated as an empty zset
        return (ZSet *)&k_empty_zset;
    }
    Entry *ent = container_of(hnode, Entry, node);
    return ent->type == T_ZSET ? &ent->zset : NULL;
}

// zrem zset name
static void do_zrem(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return resp
            ? out_resp_err(out, "expect zset")
            : out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    if (znode) {
        zset_delete(zset, znode);
    }
    return resp
        ? out_resp_int(out, znode ? 1 : 0)
        : out_int(out, znode ? 1 : 0);
}

// zscore zset name
static void do_zscore(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return resp
            ? out_resp_err(out, "expect zset")
            : out_err(out, ERR_BAD_TYP, "expect zset");
    }

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    if (resp) {
        return znode ? out_resp_dbl(out, znode->score) : out_resp_null(out);
    } else {
        return znode ? out_dbl(out, znode->score) : out_nil(out);
    }
}

// zquery zset score name offset limit
static void do_zquery(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    // parse args
    double score = 0;
    if (!str2dbl(cmd[2], score)) {
        return resp
            ? out_resp_err(out, "expect fp number")
            : out_err(out, ERR_BAD_ARG, "expect fp number");
    }
    const std::string &name = cmd[3];
    int64_t offset = 0, limit = 0;
    if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit)) {
        return resp
            ? out_resp_err(out, "expect int")
            : out_err(out, ERR_BAD_ARG, "expect int");
    }

    // get the zset
    ZSet *zset = expect_zset(cmd[1]);
    if (!zset) {
        return resp
            ? out_resp_err(out, "expect zset")
            : out_err(out, ERR_BAD_TYP, "expect zset");
    }

    // seek to the key
    if (limit <= 0) {
        return resp ? out_resp_arr_header(out, 0) : out_arr(out, 0);
    }
    ZNode *znode = zset_seekge(zset, score, name.data(), name.size());
    znode = znode_offset(znode, offset);

    // output
    if (resp) {
        // count elements first
        ZNode *tmp = znode;
        uint32_t n = 0;
        while (tmp && n/2 < (uint32_t)limit) {
            tmp = znode_offset(tmp, +1);
            n += 2;
        }
        out_resp_arr_header(out, n);
        while (znode && (int64_t)n > 0) {
            out_resp_str(out, std::string(znode->name, znode->len));
            out_resp_dbl(out, znode->score);
            znode = znode_offset(znode, +1);
            n -= 2;
        }
    } else {
        size_t ctx = out_begin_arr(out);
        int64_t n = 0;
        while (znode && n < limit) {
            out_str(out, znode->name, znode->len);
            out_dbl(out, znode->score);
            znode = znode_offset(znode, +1);
            n += 2;
        }
        out_end_arr(out, ctx, (uint32_t)n);
    }
}

static void do_subscribe(Conn* conn, std::vector<std::string> &cmd, Buffer &out, bool resp = false) {
    if (cmd.size() < 2) {
        out_resp_err(conn->outgoing, "wrong number of arguments for 'subscribe' command");
        return;
    }
    if (!conn->pubsub_mode) {
        conn->pubsub_mode = true;
        dlist_detach(&conn->idle_node);
        dlist_init(&conn->idle_node);
    }
    

    for (size_t i = 1; i < cmd.size(); i++) {
        const std::string& channel = cmd[i];
        conn->subscriptions.insert(channel);
        channels[channel].insert(conn);
        out_resp_arr_header(conn->outgoing, 3);
        out_resp_str(conn->outgoing, "subscribe");
        out_resp_str(conn->outgoing, channel);
        out_resp_int(conn->outgoing, (int64_t)conn->subscriptions.size());
    }
}

static void do_publish(std::vector<std::string> &cmd, Conn* conn, bool resp = false) {
    if (cmd.size() != 3) {
        return;
    }
    std::string channel_name = cmd[1];
    auto it = channels.find(channel_name);
    if (it == channels.end()) {
        out_resp_int(conn->outgoing, 0);
        return;
    }

    std::unordered_set<Conn*>* channel = &channels[channel_name];
    for (Conn* subscriber : *channel) {
        out_resp_str_array(subscriber->outgoing, {
            "message",
            channel_name,
            cmd[2]
        });
        subscriber->want_read = false;
        subscriber->want_write = true;
        conn_update_events(epfd, subscriber);
    }
    out_resp_int(conn->outgoing, channel->size());
}

static void do_unsubscribe(Conn* conn, std::vector<std::string>& cmd, bool resp = false) {
    if (cmd.size() == 1) {
        while (!conn->subscriptions.empty()) {
            auto it = conn->subscriptions.begin();
            std::string channel = *it;

            auto ch = channels.find(channel);
            if (ch != channels.end()) {
                ch->second.erase(conn);
                if (ch->second.empty()) {
                    channels.erase(ch);
                }
            }
            
            conn->subscriptions.erase(it);
            out_resp_arr_header(conn->outgoing, 3);
            out_resp_str(conn->outgoing, "unsubscribe");
            out_resp_str(conn->outgoing, channel);
            out_resp_int(conn->outgoing, (int64_t)conn->subscriptions.size());
        }
    } else {
        for (size_t i = 1; i < cmd.size(); i++) {
            auto it = conn->subscriptions.find(cmd[i]);
            if (it != conn->subscriptions.end()) {
                std::string channel = *it;
                auto ch = channels.find(channel);

                if (ch != channels.end()) {
                    ch->second.erase(conn);
                    if (ch->second.empty()) {
                    channels.erase(ch);
                    }
                }
                conn->subscriptions.erase(it);
            }
            out_resp_arr_header(conn->outgoing, 3);
            out_resp_str(conn->outgoing, "unsubscribe");
            out_resp_str(conn->outgoing, cmd[i]);
            out_resp_int(conn->outgoing, (int64_t)conn->subscriptions.size());
        }
    }
    if (conn->subscriptions.empty()) {
        conn->pubsub_mode = false;
        dlist_insert_before(&g_data.idle_list, &conn->idle_node);
    }
}

static void do_vset(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    if (cmd.size() != 2) {
        return resp
            ? out_resp_err(out, "usage: VSET <text>")
            : out_err(out, ERR_BAD_ARG, "usage: VSET <text>");
    }

    // check worker is alive
    if (!g_data.py_worker.to_python || !g_data.py_worker.from_python) {
        return resp
            ? out_resp_err(out, "embedding service unavailable")
            : out_err(out, ERR_UNKNOWN, "embedding service unavailable");
    }

    // get embedding from python worker
    std::string json;
    try {
        json = pyworker_embed(&g_data.py_worker, cmd[1]);
    } catch (const std::exception &e) {
        return resp
            ? out_resp_err(out, e.what())
            : out_err(out, ERR_UNKNOWN, e.what());
    }

    // parse the embedding
    std::vector<float> embedding;
    if (!parse_embedding(json, embedding)) {
        return resp
            ? out_resp_err(out, "failed to parse embedding")
            : out_err(out, ERR_UNKNOWN, "failed to parse embedding");
    }

    vdb_set(&g_data.vdb, cmd[1], embedding);
    return resp ? out_resp_str(out, "OK") : out_nil(out);
}

static void do_vdel(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    if (cmd.size() != 2) {
        return resp
            ? out_resp_err(out, "usage: VDEL <text>")
            : out_err(out, ERR_BAD_ARG, "usage: VDEL <text>");
    }

    bool deleted = vdb_del(&g_data.vdb, cmd[1]);
    return resp
        ? out_resp_int(out, deleted ? 1 : 0)
        : out_int(out, deleted ? 1 : 0);
}

static void do_vsearch(std::vector<std::string> &cmd, Buffer &out, bool resp) {
    if (cmd.size() < 2 || cmd.size() > 3) {
        return resp
            ? out_resp_err(out, "usage: VSEARCH <text> [k]")
            : out_err(out, ERR_BAD_ARG, "usage: VSEARCH <text> [k]");
    }

    // parse optional k argument, default 1
    size_t k = 1;
    if (cmd.size() == 3) {
        int64_t kval = 0;
        if (!str2int(cmd[2], kval) || kval <= 0) {
            return resp
                ? out_resp_err(out, "k must be a positive integer")
                : out_err(out, ERR_BAD_ARG, "k must be a positive integer");
        }
        k = (size_t)kval;
    }

    // check worker is alive
    if (!g_data.py_worker.to_python || !g_data.py_worker.from_python) {
        return resp
            ? out_resp_err(out, "embedding service unavailable")
            : out_err(out, ERR_UNKNOWN, "embedding service unavailable");
    }

    // embed the query
    std::string json;
    try {
        json = pyworker_embed(&g_data.py_worker, cmd[1]);
    } catch (const std::exception &e) {
        return resp
            ? out_resp_err(out, e.what())
            : out_err(out, ERR_UNKNOWN, e.what());
    }

    std::vector<float> query_embedding;
    if (!parse_embedding(json, query_embedding)) {
        return resp
            ? out_resp_err(out, "failed to parse embedding")
            : out_err(out, ERR_UNKNOWN, "failed to parse embedding");
    }

    // search
    std::vector<VSearchResult> results = vdb_search(&g_data.vdb, query_embedding, k);

    // return as flat [text, score, text, score, ...] array
    if (resp) {
        out_resp_arr_header(out, (uint32_t)(results.size() * 2));
        for (const auto &r : results) {
            out_resp_str(out, r.text);
            out_resp_dbl(out, r.score);
        }
    } else {
        size_t ctx = out_begin_arr(out);
        for (const auto &r : results) {
            out_str(out, r.text.data(), r.text.size());
            out_dbl(out, (double)r.score);
        }
        out_end_arr(out, ctx, (uint32_t)(results.size() * 2));
    }
}


enum class Cmd {
    UNKNOWN,
    GET, SET, DEL,
    PEXPIRE, PTTL, KEYS,
    ZADD, ZREM, ZSCORE, ZQUERY,
    SUBSCRIBE, UNSUBSCRIBE, PUBLISH,
    VSET, VDEL, VSEARCH,
    PING, HELLO,
};

static const std::unordered_map<std::string, Cmd> k_cmd_map = {
    {"get",         Cmd::GET},
    {"set",         Cmd::SET},
    {"del",         Cmd::DEL},
    {"pexpire",     Cmd::PEXPIRE},
    {"pttl",        Cmd::PTTL},
    {"keys",        Cmd::KEYS},
    {"zadd",        Cmd::ZADD},
    {"zrem",        Cmd::ZREM},
    {"zscore",      Cmd::ZSCORE},
    {"zquery",      Cmd::ZQUERY},
    {"subscribe",   Cmd::SUBSCRIBE},
    {"unsubscribe", Cmd::UNSUBSCRIBE},
    {"publish",     Cmd::PUBLISH},
    {"vset",        Cmd::VSET},
    {"vdel",        Cmd::VDEL},
    {"vsearch",     Cmd::VSEARCH},
    {"ping",        Cmd::PING},
    {"hello",       Cmd::HELLO},
};

static void do_request(std::vector<std::string> &cmd, Conn *conn, bool resp = false) {
    if (cmd.empty()) {
        return resp
            ? out_resp_err(conn->outgoing, "empty command")
            : out_err(conn->outgoing, ERR_BAD_ARG, "empty command");
    }

    auto it = k_cmd_map.find(cmd[0]);
    Cmd c = (it != k_cmd_map.end()) ? it->second : Cmd::UNKNOWN;

    switch (c) {
    case Cmd::GET:
        if (cmd.size() != 2) break;
        if (conn->pubsub_mode) return;
        return do_get(cmd, conn->outgoing, resp);
    case Cmd::SET:
        if (cmd.size() != 3) break;
        if (conn->pubsub_mode) return;
        return do_set(cmd, conn->outgoing, resp);
    case Cmd::DEL:
        if (cmd.size() != 2) break;
        if (conn->pubsub_mode) return;
        return do_del(cmd, conn->outgoing, resp);
    case Cmd::PEXPIRE:
        if (cmd.size() != 3) break;
        if (conn->pubsub_mode) return;
        return do_expire(cmd, conn->outgoing, resp);
    case Cmd::PTTL:
        if (cmd.size() != 2) break;
        if (conn->pubsub_mode) return;
        return do_ttl(cmd, conn->outgoing, resp);
    case Cmd::KEYS:
        if (cmd.size() != 1) break;
        if (conn->pubsub_mode) return;
        return do_keys(cmd, conn->outgoing, resp);
    case Cmd::ZADD:
        if (cmd.size() != 4) break;
        if (conn->pubsub_mode) return;
        return do_zadd(cmd, conn->outgoing, resp);
    case Cmd::ZREM:
        if (cmd.size() != 3) break;
        if (conn->pubsub_mode) return;
        return do_zrem(cmd, conn->outgoing, resp);
    case Cmd::ZSCORE:
        if (cmd.size() != 3) break;
        if (conn->pubsub_mode) return;
        return do_zscore(cmd, conn->outgoing, resp);
    case Cmd::ZQUERY:
        if (cmd.size() != 6) break;
        if (conn->pubsub_mode) return;
        return do_zquery(cmd, conn->outgoing, resp);
    case Cmd::SUBSCRIBE:
        if (cmd.size() < 2) break;
        return do_subscribe(conn, cmd, conn->outgoing, resp);
    case Cmd::UNSUBSCRIBE:
        if (cmd.size() < 1) break;
        return do_unsubscribe(conn, cmd, resp);
    case Cmd::PUBLISH:
        if (cmd.size() != 3) break;
        return do_publish(cmd, conn, resp);
    case Cmd::VSET:
        if (cmd.size() != 2) break;
        if (conn->pubsub_mode) return;
        return do_vset(cmd, conn->outgoing, resp);
    case Cmd::VDEL:
        if (cmd.size() != 2) break;
        if (conn->pubsub_mode) return;
        return do_vdel(cmd, conn->outgoing, resp);
    case Cmd::VSEARCH:
        if (cmd.size() < 2 || cmd.size() > 3) break;
        if (conn->pubsub_mode) return;
        return do_vsearch(cmd, conn->outgoing, resp);
    case Cmd::PING:
        if (cmd.size() != 1) break;
        return resp
            ? out_resp_str(conn->outgoing, "PONG")
            : out_str(conn->outgoing, "PONG", 4);
    case Cmd::HELLO:
        out_resp_arr_header(conn->outgoing, 14);
        out_resp_str(conn->outgoing, "server");  out_resp_str(conn->outgoing, "redis");
        out_resp_str(conn->outgoing, "version"); out_resp_str(conn->outgoing, "7.0.0");
        out_resp_str(conn->outgoing, "proto");   out_resp_int(conn->outgoing, 2);
        out_resp_str(conn->outgoing, "id");      out_resp_int(conn->outgoing, conn->fd);
        out_resp_str(conn->outgoing, "mode");    out_resp_str(conn->outgoing, "standalone");
        out_resp_str(conn->outgoing, "role");    out_resp_str(conn->outgoing, "master");
        out_resp_str(conn->outgoing, "modules"); out_resp_arr_header(conn->outgoing, 0);
        return;
    default:
        break;
    }
    return resp
        ? out_resp_err(conn->outgoing, "unknown command")
        : out_err(conn->outgoing, ERR_UNKNOWN, "unknown command");
}

static void response_begin(Buffer &out, size_t *header) {
    *header = out.size();       // messege header position
    buf_append_u32(out, 0);     // reserve space
}
static size_t response_size(Buffer &out, size_t header) {
    return out.size() - header - 4;
}
static void response_end(Buffer &out, size_t header) {
    size_t msg_size = response_size(out, header);
    if (msg_size > k_max_msg) {
        out.resize(header + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header);
    }
    // message header
    uint32_t len = (uint32_t)msg_size;
    memcpy(&out[header], &len, 4);
}

static bool try_one_request_resp(Conn* conn) {
    const uint8_t *data = conn->incoming.data() + conn->incoming_start;
    size_t size = conn->incoming.size() - conn->incoming_start;

    if (size < 4) return false;
    if (data[0] != '*') {
        msg("invalid RESP: expected *");
        conn->want_close = true;
        return false;
    }

    // find end of first line
    const uint8_t *end = (const uint8_t *)memchr(data, '\n', size);
    if (!end) return false;

    int nargs = atoi((char *)data + 1);
    if (nargs <= 0 || nargs > (int)k_max_args) {
        msg("invalid RESP: bad nargs");
        conn->want_close =  true;
        return false;
    }

    std::vector<std::string> cmd;
    cmd.reserve(nargs);
    const uint8_t* cur = end + 1;
    for (int i = 0; i < nargs; i++) {
        if (cur >= data + size || *cur != '$') return false;

        // find end of the length line
        const uint8_t* lend = (const uint8_t *)memchr(cur, '\n', (data + size) - cur);
        if (!lend) return false;

        int len = atoi((char *)cur + 1);
        if (len < 0) {
            msg("invalid RESP: bad bulk length");
            conn->want_close = true;
            return false;
        }
        cur = lend + 1;
        // check we have len bytes + \r\n
        if (cur + len + 2 > data + size) return false;

        cmd.push_back(std::string((char *)cur, len));
        cur += len + 2;  // skip data and \r\n
    }
    for (auto &c : cmd[0]) c = tolower(c);

    do_request(cmd, conn, true);
    conn_consume_incoming(conn, cur - data);
    return true;
}

// process 1 request if there is enough data
static bool try_one_request(Conn* conn) {
    // try to parse the protocol: message header
    uint8_t* data = conn->incoming.data() + conn->incoming_start;
    size_t size = conn->incoming.size() - conn->incoming_start;

    if (size < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, data, 4);
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;   // want close
    }
    // message body
    if (4 + len > size){
        return false;   // want read
    }
     const uint8_t* request = data + 4;

    // got one request, do some application logic
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        msg("bad request");
        conn->want_close = true;
        return false;   // want close
    }
    size_t header_pos = 0;
    response_begin(conn->outgoing, &header_pos);
    do_request(cmd, conn);
    response_end(conn->outgoing, header_pos);

    // application logic done! remove the request message.
    conn_consume_incoming(conn, 4 + len);
    
    return true;        // success
}

// application callback when the socket is writable
static void handle_write(int epfd, Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;    // error handling
        return;
    }

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    // update the readiness intention
    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
        conn_update_events(epfd, conn);
    } // else: want write
}

// application callback when the socket is readable
static void handle_read(int epfd, Conn *conn) {
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return; // actually not ready
    }
    // handle IO error
    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }
    // handle EOF
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            msg("client closed");
        } else {
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }
    // got some new data
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse requests and generate responses
    if (conn->proto == Conn::PROTO_RESP) {
        while (try_one_request_resp(conn)) {}
    } else {
        while (try_one_request(conn)) {}
    }
    
    

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        conn_update_events(epfd, conn);
        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(epfd, conn);
    }   // else: want read
}

static void conn_update_events(int epfd, Conn *conn) {
    epoll_event ev{};
    if (conn->want_read) {
        ev.events |=  EPOLLIN;
    }
    if (conn->want_write) {
        ev.events |= EPOLLOUT;
    }
    ev.data.ptr = conn;
    if (epoll_ctl(epfd, EPOLL_CTL_MOD, conn->fd, &ev) < 0) {
        msg_errno("epoll_ctl(MOD)");
    }
}



static uint32_t next_timer_ms(uint64_t idle_timeout_ms) {
    uint64_t now_ms = get_monotonic_msec();
    uint64_t next_ms = (uint64_t)-1;
    // idle timers using a linked list
    if (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        next_ms = conn->last_active_ms + idle_timeout_ms;
    }
    // TTL timers using a heap
    if (!g_data.heap.empty() && g_data.heap[0].val < next_ms) {
        next_ms = g_data.heap[0].val;
    }
    // timeout value
    if (next_ms == (uint64_t)-1) {
        return -1;  // no timers, no timeouts
    }
    if (next_ms <= now_ms) {
        return 0;   // missed?
    }
    return (int32_t)(next_ms - now_ms);
}

static bool hnode_same(HNode *node, HNode *key) {
    return node == key;
}

static void process_timers(int epfd, uint64_t idle_timeout_ms) {
    uint64_t now_ms = get_monotonic_msec();
    // idle timers using a linked list
    while (!dlist_empty(&g_data.idle_list)) {
        Conn *conn = container_of(g_data.idle_list.next, Conn, idle_node);
        uint64_t next_ms = conn->last_active_ms + idle_timeout_ms;
        if (next_ms >= now_ms) {
            break;  // not expired
        }

        fprintf(stderr, "removing idle connection: %d\n", conn->fd);
        conn_destroy(epfd, conn);
    }
    // TTL timers using a heap
    const size_t k_max_works = 2000;
    size_t nworks = 0;
    const std::vector<HeapItem> &heap = g_data.heap;
    while (!heap.empty() && heap[0].val < now_ms) {
        Entry *ent = container_of(heap[0].ref, Entry, heap_idx);
        HNode *node = hm_delete(&g_data.db, &ent->node, &hnode_same);
        assert(node == &ent->node);
        // fprintf(stderr, "key expired: %s\n", ent->key.c_str());
        // delete the key
        entry_del(ent);
        if (nworks++ >= k_max_works) {
            // don't stall the server if too many keys are expiring at once
            break;
        }
    }
}

static uint64_t last_save_ms = 0;
const uint64_t save_interval_ms = 10 * 1000; // every 60s

int main(int argc, char* argv[]) {
    int max_events = 1024;
    uint64_t idle_timeout_ms = 5 * 1000;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--max-events")== 0 && i + 1 < argc) {
            max_events = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--idle-timeout") == 0 && i + 1 < argc) {
            idle_timeout_ms = atoll(argv[++i]);
        }
    }

    struct ListenerTag { int fd; Conn::Proto proto; };
    // initialization
    dlist_init(&g_data.idle_list);
    thread_pool_init(&g_data.thread_pool, 4);
    if (!persist_load(&g_data.db)) {
        fprintf(stderr, "warning: failed to load dump.rdb\n");
    }

    try {
        pyworker_start(&g_data.py_worker, "python_worker.py");
    } catch (const std::exception &e) {
        fprintf(stderr, "warning: failed to start python worker: %s\n", e.what());
        fprintf(stderr, "VSET/VSEARCH/VDEL will return errors until worker is available\n");
    }

    // binary protocol socket on port 1234
    int fd_binary = socket(AF_INET, SOCK_STREAM, 0);
    if (fd_binary < 0) {
        die("socket()");
    }
    int val = 1;
    setsockopt(fd_binary, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0);    // wildcard address 0.0.0.0
    int rv = bind(fd_binary, (const sockaddr *)&addr, sizeof(addr));
    if (rv) {
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd_binary);

    // listen
    rv = listen(fd_binary, SOMAXCONN);
    if (rv) {
        die("listen()");
    }
    ListenerTag tag_binary = {fd_binary, Conn::PROTO_BINARY};

    // RESP protocol socket on port 6379
    int fd_resp = socket(AF_INET, SOCK_STREAM, 0);
    if (fd_resp < 0) { die("socket()"); }
    setsockopt(fd_resp, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));
    struct sockaddr_in addr_resp = {};
    addr_resp.sin_family = AF_INET;
    addr_resp.sin_port = ntohs(6379);
    addr_resp.sin_addr.s_addr = ntohl(0);
    rv = bind(fd_resp, (const sockaddr *)&addr_resp, sizeof(addr_resp));
    if (rv) { die("bind()"); }
    fd_set_nb(fd_resp);
    rv = listen(fd_resp, SOMAXCONN);
    if (rv) { die("listen()"); }
    ListenerTag tag_resp   = {fd_resp,   Conn::PROTO_RESP};

    // epoll instance
    epfd = epoll_create1(0);
    if (epfd < 0) {
        die("epoll_create1()");
    }

    struct epoll_event ev_binary{};
    ev_binary.events = EPOLLIN;
    ev_binary.data.ptr = &tag_binary;

    if (epoll_ctl(epfd, EPOLL_CTL_ADD, fd_binary, &ev_binary) < 0) {
        die("epoll_ctl(ADD)");
    }

    struct epoll_event ev_resp{};
    ev_resp.events = EPOLLIN;
    ev_resp.data.ptr   = &tag_resp;

    if (epoll_ctl(epfd, EPOLL_CTL_ADD, fd_resp, &ev_resp) < 0) {
        die("epoll_ctl(ADD)");
    }

    signal(SIGINT, handle_sigint);
    signal(SIGTERM, handle_sigint);
    // the event loop
    while (true) {
        // wait for readiness
        int32_t timeout_ms = next_timer_ms(idle_timeout_ms);
        std::vector<epoll_event> events(max_events);
        int n = epoll_wait(epfd, events.data(), max_events, timeout_ms);
        if (n < 0 && errno == EINTR) {
            continue;   // not an error
        }
        if (n < 0) {
            die("epoll_wait");
        }

        // handle listening sockets
        for (int i = 0; i < n; i++) {
            void *ptr = events[i].data.ptr;
            if (ptr == &tag_binary || ptr == &tag_resp) {
                ListenerTag* tag = (ListenerTag *)ptr;
                handle_accept(epfd, tag->fd, tag->proto);
            } else {
                Conn* conn = static_cast<Conn *>(events[i].data.ptr);
                uint32_t ready = events[i].events;
                // update the idle timer by moving conn to the end of the list
                if (!conn->pubsub_mode) {
                    conn->last_active_ms = get_monotonic_msec();
                    dlist_detach(&conn->idle_node);
                    dlist_insert_before(&g_data.idle_list, &conn->idle_node);
                }
                
                if (ready & EPOLLIN) {
                    handle_read(epfd, conn);
                }
                
                if ((ready & (EPOLLERR | EPOLLHUP)) || conn->want_close) {
                    conn_destroy(epfd, conn);
                    continue;  // skip the EPOLLOUT check
                }
                if (ready & EPOLLOUT) {
                    handle_write(epfd, conn);
                }
                if (conn->want_close) {
                    conn_destroy(epfd, conn);
                }
            }
            
        }
        // handle timers
        process_timers(epfd, idle_timeout_ms);

        uint64_t now = get_monotonic_msec();
        if (now - last_save_ms >= save_interval_ms) {
            persist_save(&g_data.db);
            last_save_ms = now;
        }
    }   // the event loop
    return 0;
}